- name: 关闭firewalld NetworkManager dnsmasq - CentOS
  systemd: 
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - firewalld
    - NetworkManager
    - dnsmasq
  ignore_errors: True

- name: 临时关闭 selinux
  shell: "setenforce 0"
  failed_when: false

- name: 永久关闭 selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"


# 优化设置 journal 日志相关，避免日志重复搜集，浪费系统资源
- name: 禁止rsyslog获取journald日志
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    regexp: "{{ item }}"
    line: '#\1'
    backrefs: yes
  with_items:
  - '(^\$ModLoad imjournal)'
  - '(^\$IMJournalStateFile)'

- name: 修改systemctl启动的最小文件打开数量
  lineinfile:
    dest: /etc/systemd/system.conf
    state: present
    regexp: "^#{{ item.key }}"
    line: "\\1={{ item.value }}"
    backrefs: yes
  with_items:
  - { key: '(DefaultLimitCORE)=', value: '100000' }
  - { key: '(DefaultLimitNOFILE)=', value: '100000' }

- name: 添加EPEL仓库
  yum: name=epel-release state=latest update_cache=yes

- name: 安装基础软件包
  yum: 
    name: 
      - conntrack-tools     # ipvs 模式需要
      - psmisc        # 安装psmisc 才能使用命令killall，它在keepalive的监测脚本中使用到
      - nfs-utils     # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - jq                  # 轻量JSON处理程序，安装docker查询镜像需要
      - socat               # 用于port forwarding
      - bash-completion     # bash命令补全工具，需要重新登录服务器生效
      - ipset
      - perl           # 内核依赖
      - ipvsadm
      - iptables
      - conntrack
      - libseccomp
      - net-tools
      - crontabs
      - sysstat
      - unzip
      - bind-utils
      - tcpdump
      - telnet
      - lsof
      - nload
      - strace
      - bridge-utils
      - iftop
      - htop
      - wget
      - psmisc
    state: latest
    update_cache: yes


- block:
    - name: 导入GPG key
      rpm_key:
        state: present
        key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    
    - name: 导入elrepo
      yum:
        name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
        state: present
    
    - name: 升级到最新内核
      yum:
        name: 
          - kernel-ml
          - kernel-ml-devel
        disablerepo: "*"
        enablerepo: "elrepo-kernel"
      tags:
        - kernel
    
    - name: 修改默认启动内核到新内核
      shell: grub2-set-default  0 && grub2-mkconfig -o /etc/grub2.cfg
  when: kernel

- name: 设置内核参数适应docker
  shell: |
    grubby --args="user_namespace.enable=1" --update-kernel=$(grubby --default-kernel)

- name: 物理机下调整cpu到非省电模式
  command: tuned-adm profile throughput-performance
  when: ansible_virtualization_role == 'host'
